### ISSUE TITLE
Roadmap H1 2019

### ISSUE THREAD

**Issue by dharmjit** [play-makers/DevilConnect#1]
## Devils Connect RoadMap for 2019 H1
- [ ] Meetings/Discussions Planning
- [ ] Company Website
- [ ] UI Mockups
- [ ] Technical Architecture Designs
- [ ] Tech Stacks/Languages/Frameworks Decisions
- [ ] Platform Finalisation
- [ ] API Specifications
